version: "3.7"

services: 
  website-php:
    build: 
      context: ./
      dockerfile: .docker/php-nginx_buster/Dockerfile
    # image: richarvey/nginx-php-fpm:latest
    # volumes:
    #  - ./:/var/www/html/laravel
    ports:
     - "8080:80"